export const homePage_cn = {
  json: 'JSON 格式化',
  jsonDescription: 'JSON 格式化与压缩工具',
  regx: '正则表达式',
  regxDescription: '正则表达式测试工具',
  uuid: 'UUID 生成器',
  uuidDescription: '生成 UUID 标识符',
  encoding: '编码转换',
  encodingDescription: '文件编码格式转换工具',
  jwt: 'JWT 解析',
  jwtDescription: 'JWT Token 解析与编码工具',
  csv_generate: 'CSV做成',
  csv_generateDescription: '自定义模板批量生成CSV文件',
  sql_format: 'SQL格式化',
  sql_formatDescription: '粘贴SQL代码或存储过程代码，自动格式化换行、对齐等，让SQL语句美观。',
  folder_tree: '文档树生成',
  folder_treeDescription: '选择文件夹自动生成文档树结构',
  base64: 'Base64 编解码',
  base64Description: 'Base64 编码与解码工具',
  crypto_hash: '哈希加密',
  crypto_hashDescription: 'SHA256/SHA512 哈希计算工具',
  xml_format: 'XML 格式化',
  xml_formatDescription: 'XML 格式化与压缩工具',
  url_encode: 'URL 编码',
  url_encodeDescription: 'URL 编码与解码工具',
  unicode_trans: 'Unicode 转码',
  unicode_transDescription: 'ASCII/Unicode/中文互相转换工具',
  lang_detect: '代码语言检测',
  lang_detectDescription: '检测代码中是否包含指定语言字符',
  favorite: '收藏',
  unfavorite: '取消收藏'
}


export const homePage_jp = {
  json: 'JSON フォーマッター',
  jsonDescription: 'JSONフォーマットと圧縮ツール',
  regx: '正規表現',
  regxDescription: '正規表現テストツール',
  uuid: 'UUID ジェネレーター',
  uuidDescription: 'UUID 識別子を生成',
  encoding: 'エンコード変換',
  encodingDescription: 'ファイルエンコード変換ツール',
  jwt: 'JWT パーサー',
  jwtDescription: 'JWT トークン解析・エンコードツール',
  csv_generate: 'CSV作成',
  csv_generateDescription: 'テンプレートでCSVファイルを一括生成',
  sql_format: 'SQL整形',
  sql_formatDescription: 'SQL文やストアドプロシージャを貼り付けて、自動で整形・改行・インデントを行い、SQLを見やすくします。',
  folder_tree: 'ドキュメントツリー生成',
  folder_treeDescription: 'フォルダを選択してドキュメントツリー構造を自動生成',
  base64: 'Base64 エンコード/デコード',
  base64Description: 'Base64 エンコード・デコードツール',
  crypto_hash: 'ハッシュ暗号化',
  crypto_hashDescription: 'SHA256/SHA512 ハッシュ計算ツール',
  xml_format: 'XML フォーマッター',
  xml_formatDescription: 'XMLフォーマットと圧縮ツール',
  url_encode: 'URL エンコード',
  url_encodeDescription: 'URL エンコード・デコードツール',
  unicode_trans: 'Unicode 変換',
  unicode_transDescription: 'ASCII/Unicode/中国語相互変換ツール',
  lang_detect: 'コード言語検出',
  lang_detectDescription: 'コード内の指定言語文字を検出',
  favorite: 'お気に入り',
  unfavorite: 'お気に入り解除'
}